version: "3.6"

networks:
  appnetwork:
    driver: bridge

services:
  fcrepo:
    container_name: fcrepo
    build:
      context: ./docker/services/fcrepo
      args:
        FEDORA_VERSION: 5.0.2
        FEDORA_TAG: 5.0.2
        ModeshapeConfig: jdbc-postgresql
        JDBCConfig: -Dfcrepo.postgresql.username=fcrepoadmin -Dfcrepo.postgresql.password=fcrepoadminpw -Dfcrepo.postgresql.host=fcrepo-postgres.fcrepo -Dfcrepo.postgresql.port=5432
    image: fcrepo
    networks:
      appnetwork:
        aliases:
          - fcrepo
    ports:
      - 8080:8080
      
