version: "3.6"

networks:
  appnetwork:
    driver: bridge

services:
  fcrepo:
    container_name: fcrepo
    build:
      context: .
      depends_on: postgres
      args:
        FEDORA_TAG: 5.0.2
        ModeshapeConfig: jdbc-postgresql
        JAVA_OPTS: -Dfcrepo.postgresql.username=fcrepoadmin -Dfcrepo.postgresql.password=fcrepoadminpw -Dfcrepo.postgresql.host=fcrepo-postgres.fcrepo -Dfcrepo.postgresql.port=5432
    image: fcrepo
    ports:
      - 8080:8080
    networks:
      appnetwork:
        aliases:
          - fcrepo
  postgres:
    container_name: postgres
    image: postgres:9
    networks:
      appnetwork:
        aliases:
          - fcrepo-postgres.fcrepo
    environment:
      POSTGRES_USER: fcrepoadmin
      POSTGRES_PASSWORD: fcrepoadminpw
      POSTGRES_DB: fcrepo
