apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fcrepo5
  name: fcrepo5
  namespace: fcrepo
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fcrepo5
    spec:
      volumes:
      - name: fcrepo-data
        persistentVolumeClaim:
          claimName: fcrepo-pv-claim
      containers:
      - name: fcrepo5
        volumeMounts:
        - name: fcrepo-data
          mountPath: "/mnt/fcrepo-data"
        image: oliverar/fcrepo:5.0.2
        env:
        - name: JAVA_OPTS
          value: "-Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.home=/mnt/fcrepo-data -Dfcrepo.audit.container=/mnt/audit -Dfcrepo.postgresql.username=fcrepoadmin -Dfcrepo.postgresql.password=fcrepoadminpw -Dfcrepo.postgresql.host=fcrepo-postgres.fcrepo -Dfcrepo.postgresql.port=5432"
        ports:
        - containerPort: 8080
      restartPolicy: Always
