apiVersion: v1
kind: Service
metadata:
  name: fcrepo-postgres
  namespace: fcrepo
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: fcrepo5-postgres
